[package]
name = "eventloop"
version = "0.1.0"
authors = ["anil1596 <anil.khadwal@gmail.com>"]

build = "build.rs"

[dependencies]
libc = "0.2"
lazy_static = "0.2.1"

[build-dependencies]
gcc="0.3.0"
